/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        canvas: "#000000",
        surface: {
          soft: "#0d0d0d",
          card: "#141414",
          elevated: "#1f1f1f",
        },
        hairline: {
          DEFAULT: "#262626",
          strong: "#3a3a3a",
        },
        ink: "#ffffff",
        body: {
          DEFAULT: "#cccccc",
          strong: "#e6e6e6",
        },
        muted: {
          DEFAULT: "#999999",
          soft: "#757575",
        },
        link: "#c3d9f3",
        warning: "#d4a017",
        success: "#5fa657",
        danger: "#e05252",
        chart: {
          1: "#60a5fa",
          2: "#f87171",
          3: "#4ade80",
          4: "#fb923c",
          5: "#c084fc",
          6: "#22d3ee",
          7: "#facc15",
          8: "#f472b6",
          9: "#a5b4fc",
          10: "#34d399",
          11: "#fbbf24",
          12: "#e879f9",
          13: "#38bdf8",
          14: "#fb7185",
          15: "#a3e635",
          16: "#d946ef",
          17: "#2dd4bf",
          18: "#fca5a5",
          19: "#93c5fd",
          20: "#fcd34d",
        },
      },
      fontFamily: {
        display: ['"Saira Condensed"', "sans-serif"],
        serif: ['"EB Garamond"', "Georgia", "serif"],
        mono: ['"IBM Plex Mono"', "ui-monospace", "SFMono-Regular", "monospace"],
      },
      borderRadius: {
        none: "0px",
        pill: "9999px",
        full: "9999px",
      },
      letterSpacing: {
        wordmark: "6px",
        display: "4px",
        "display-lg": "3px",
        "display-md": "2px",
        "display-sm": "1.5px",
        "display-xs": "1px",
        label: "2.5px",
        "label-sm": "2px",
      },
    },
  },
  plugins: [],
};
