// <auto-generated />
using System;
using HotelScraper.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelScraper.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260901212251_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0-preview.2.25163.8");

            modelBuilder.Entity("HotelScraper.Api.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active");

                    b.Property<string>("Address")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<string>("BookingId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("booking_id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("city");

                    b.Property<double?>("DistanceKm")
                        .HasColumnType("REAL")
                        .HasColumnName("distance_km");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<double?>("ReviewScore")
                        .HasColumnType("REAL")
                        .HasColumnName("review_score");

                    b.Property<int?>("Stars")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stars");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("City");

                    b.HasIndex("BookingId", "City")
                        .IsUnique()
                        .HasDatabaseName("uq_booking_city");

                    b.HasIndex(new[] { "BookingId", "City" }, "uq_booking_city")
                        .IsUnique();

                    b.ToTable("hotels");
                });

            modelBuilder.Entity("HotelScraper.Api.Data.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("fetched_at");

                    b.Property<int>("HotelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hotel_id");

                    b.Property<double>("PriceEur")
                        .HasColumnType("REAL")
                        .HasColumnName("price_eur");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("room_type");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("HotelId");

                    b.HasIndex("HotelId", "Date", "RoomType")
                        .IsUnique()
                        .HasDatabaseName("uq_hotel_date_room");

                    b.HasIndex(new[] { "HotelId", "Date", "RoomType" }, "uq_hotel_date_room")
                        .IsUnique();

                    b.ToTable("prices");
                });

            modelBuilder.Entity("HotelScraper.Api.Data.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("settings");
                });
#pragma warning restore 612, 618
        }
    }
}
